baseURL = 'http://leo.resier.net/'
languageCode = 'en-us'
title = "Leo's Blog"
theme = 'hugo-theme-cleanwhite'
paginate = 5

[params]
  header_image = "img/myPicture.jpg"
  omit_categories = true

[[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/about/"